version: '3'
services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "8080:8080"

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
