version: '3'
services:
  webapp:
    build:
      context: ./
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
